version: 0.2

phases:
  build:
    commands:
      - java -version
      - mvn clean package -Ddb_user${db_user} -Ddb_pass${db_pass} -Ddb_url${db_url}
artifacts:
  files:
    - 'Dockerfile'
    - target/eCommerceP2-0.0.1-SNAPSHOT.jar